### PR TITLE
fix(Notification): Fixed an issue where Notification was automatically destroyed in the background, fixed #159

### LINKED ISSUE #159: App后台运行，Notification自动隐藏
## 组件

Notification

## 版本

- 组件版本：4.7.9
- react 版本：16.8.3
- react-native 版本：5.30

## 概述

Notification 显示时，使 APP 进入后台运行，数据没有变化，也没有手动将关闭通知，Notification 会自动隐藏

## 重现步骤

1. 显示 Notification
2. APP 进入后台
3. Notification 会自动消失

## Bug 行为

Notification 自动隐藏

## 期望行为

Notification 不要自动隐藏

## 期望发布日期

**

## 附件

https://user-images.githubusercontent.com/57558007/141935118-99e2088f-36d4-4961-b096-4cd138fff6ee.mp4

### PR DESCRIPTION
**Pull request by ZengBeauty**
## Description

fix(Notification): Fixed an issue where Notification was automatically destroyed in the background, fixed #159.

## Type of change

Please select the relevant option.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

File: packages/tuya-panel-kit/src/components/layout/navigator-layout/index.js [hunk 1]
```diff
@@ -74,6 +74,7 @@ export default class NavigatorLayout extends Component {
     }
     this.state = {
       modalVisible: false,
+      mqttState: false,
```
Comment (ShinyLeee) [inline packages/tuya-panel-kit/src/components/layout/navigator-layout/index.js:77]: 变量名建议优化下，应该是是否是否后台运行中？

Comment (ZengBeauty) [reply packages/tuya-panel-kit/src/components/layout/navigator-layout/index.js:77]: 这是根据 mqtt 弹框的状态来判断是否监控 AppState，只涉及到 Mqtt 弹框的那一块逻辑

Comment (ZengBeauty) [reply packages/tuya-panel-kit/src/components/layout/navigator-layout/index.js]: 改成 isMqttNoticeActive：Mqtt 弹框是否存在

**Review by youngjuning — APPROVED** [review]
